
version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - rri-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - rri-network
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - rri-network

networks:
  rri-network:
    driver: bridge

volumes:
  dbdata:
